### ISSUE TITLE
scheduler error

### ISSUE THREAD

**Issue by hegaoye** [mbonaci/solr-data-import-scheduler#2]
这个是怎么回事呢？

<index update process> Full URL
http://127.0.0.1:8080/solr/new_core/select?qt=/dataimport&command=delta-import&clean=false&commit=true
788517 ERROR (http-apr-8080-exec-1) [   new_core] o.a.s.c.SolrCore org.apache.solr.common.SolrException: Bad contentType for search handler :null request={qt=/dataimport&commit=true&clean=false&command=delta-import}
        at org.apache.solr.request.json.RequestUtil.processParams(RequestUtil.java:73)
        at org.apache.solr.util.SolrPluginUtils.setDefaults(SolrPluginUtils.java:166)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:140)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1984)
        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:829)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:446)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:220)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:217)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:105)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)

**Comment by hegaoye** [comment]
solr 5.1 tomcat 9 jdk 1.8

**Comment by mbonaci** [comment]
Yeah, you can see in the changelog in the readme that this was written in 2010. Now I added additional info on top of readme.  

I think that, in order to make this work, you'd have to refactor the URL schema of REST requests to fit the latest Solr version and I don't have time now to go into this.  

I'll, of course, accept any such pull request :)

**Comment by Gabriel-Rhee** [comment]
Thanks mbonaci for this library.
I used it but need to proceed some modification for my environment(Solr 5.4/Tomcat v8).
There are two modification on your code as follows

1) SolrDataImportProperties.java
SolrResourceLoader couldn't find the properties file by default therefore i modified the code 

```
Path path = SolrResourceLoader.locateSolrHome();
String configDir = SolrResourceLoader.normalizeDir(path.toString());
```

2) HttpPostScheduler.java
In my case there is a "Bad contentType" issue when the context type is "application/html".

```
conn.setRequestProperty("Content-Type","application/x-www-form-urlencoded");
```

After i changed those things it works fine.
I hope this is helpful^^.

**Comment by mbonaci** [comment]
Hi @Gabriel-Rhee, 
thanks for that. Could you possible package that in the form of pull request?
If you need help, just ask. Thx

**Comment by BhargavaRavaliKoganti** [comment]
@Gabriel-Rhee, Is it possible to share the Updated jar file?
